import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {build} from '../node_modules/.pnpm/esbuild@0.28.0/node_modules/esbuild/lib/main.js';
import assert from 'node:assert/strict';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../drizzle/0000_loving_mandroid.sql',import.meta.url),'utf8'));
function prepare(sql){let args=[];return{bind(...a){args=a;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return{results:sqlite.prepare(sql).all(...args)}},async run(){return sqlite.prepare(sql).run(...args)}}}
globalThis.__testEnv={DB:{prepare,async batch(stmts){sqlite.exec('BEGIN');try{const results=[];for(const s of stmts)results.push(await s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}},ADMIN_EMAILS:'admin@example.test',COMMERCE_MODE:'demo'};
mkdirSync('.sites-runtime/tests',{recursive:true});await build({entryPoints:['lib/commerce.ts'],bundle:true,platform:'node',format:'esm',outfile:'.sites-runtime/tests/commerce.mjs',plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env=globalThis.__testEnv;',loader:'js'}))}}]});
const {handleCommerce}=await import('../.sites-runtime/tests/commerce.mjs');
const guest=crypto.randomUUID();let checks=0;
async function call(path,body,options={}){const headers={cookie:'shrinika_guest='+guest,origin:'https://store.test','content-type':'application/json',...options.headers};if(options.admin){headers['oai-authenticated-user-id']='admin-user';headers['oai-authenticated-user-email']='admin@example.test'}const r=await handleCommerce(new Request('https://store.test/api/commerce/'+path,{method:options.method||(body?'POST':'GET'),headers,body:body?JSON.stringify(body):undefined}));const data=await r.json();if(options.status)assert.equal(r.status,options.status,JSON.stringify(data));else assert.ok(r.ok,JSON.stringify(data));checks++;return data}
const b=await call('bootstrap');assert.equal(b.products.length,6);assert.equal(b.admin,false);
await call('admin/dashboard',null,{status:403});await call('admin/dashboard',null,{admin:true});
await call('quote',{items:[{variantId:'amber-50',quantity:-1}]},{status:400});
const q=await call('quote',{items:[{variantId:'amber-50',quantity:1}],coupon:'WELCOME10',total:1});assert.equal(q.total,234000);assert.equal(q.discount,24900);
await call('quote',{items:[{variantId:'amber-50',quantity:1}],coupon:'INVALID'},{status:400});
await call('cart',{items:[{variantId:'amber-50',quantity:1}],coupon:''},{method:'PUT'});assert.equal((await call('cart')).items.length,1);
await call('cart',{items:[]},{method:'PUT',headers:{origin:'https://evil.test'},status:403});
const customer={name:'Demo Customer',email:'customer@example.test',phone:'9999999999',line1:'123 Sample Road',line2:'',city:'Sample City',state:'Sample State',postal:'110001'};
const input={items:[{variantId:'amber-50',quantity:1}],coupon:'WELCOME10',customer,key:crypto.randomUUID(),guest:true};
const created=await call('checkout',input);assert.equal(created.order.total,234000);assert.ok(created.accessCode);const again=await call('checkout',input);assert.equal(again.order.id,created.order.id);assert.equal(sqlite.prepare('SELECT stock FROM variants WHERE id=?').get('amber-50').stock,24);
await call('orders/'+created.order.id,null,{headers:{cookie:'shrinika_guest='+crypto.randomUUID()},status:404});
await call('track',{number:created.order.number,accessCode:'wrong'},{headers:{cookie:'shrinika_guest='+crypto.randomUUID()},status:404});
assert.equal((await call('track',{number:created.order.number,accessCode:created.accessCode},{headers:{cookie:'shrinika_guest='+crypto.randomUUID()}})).order.id,created.order.id);
const paid=await call('demo-payment',{id:created.order.id});assert.equal(paid.order.payment_status,'demo');await call('demo-payment',{id:created.order.id});assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM order_events WHERE id=?').get('demo-'+created.order.id).n,1);
await call('admin/order',{id:created.order.id,status:'delivered'},{admin:true,status:400});
await call('admin/order',{id:created.order.id,status:'processing'},{admin:true});await call('admin/order',{id:created.order.id,status:'shipped',carrier:'Demo Courier',trackingNumber:'DEMO-001',trackingUrl:'https://example.test/track'},{admin:true});await call('admin/order',{id:created.order.id,status:'delivered'},{admin:true});
const c=structuredClone(b.content);c.heroTitle='A changed draft';await call('admin/content',{content:c,publish:false},{admin:true});assert.notEqual((await call('bootstrap')).content.heroTitle,c.heroTitle);await call('admin/content',{content:c,publish:true},{admin:true});assert.equal((await call('bootstrap')).content.heroTitle,c.heroTitle);
const p=b.products[0];p.variants[0].stock=0;await call('admin/product',p,{admin:true});await call('checkout',{...input,key:crypto.randomUUID()},{status:409});
// Rollback protects every stock row if a competing reservation exhausts inventory.
const before=sqlite.prepare('SELECT stock FROM variants WHERE id=?').get('rose-50').stock;try{await globalThis.__testEnv.DB.batch([prepare('UPDATE variants SET stock=stock-1 WHERE id=?').bind('rose-50'),prepare('UPDATE variants SET stock=stock-1 WHERE id=?').bind('amber-50')])}catch{}assert.equal(sqlite.prepare('SELECT stock FROM variants WHERE id=?').get('rose-50').stock,before);
console.log(`PASS: ${checks} API checks; guest isolation, admin access, pricing, promotions, idempotency, inventory rollback, tracking, fulfilment and draft publication.`);
const {createHmac}=await import('node:crypto');globalThis.__testEnv.RAZORPAY_KEY_ID='rzp_test_fixture';globalThis.__testEnv.RAZORPAY_KEY_SECRET='fixture-secret';globalThis.__testEnv.RAZORPAY_WEBHOOK_SECRET='fixture-webhook';let providerOrder,providerPayment,providerStatus='authorized';globalThis.fetch=async(url,options)=>{if(String(url).endsWith('/orders')){const payload=JSON.parse(options.body);providerOrder={id:'order_fixture',amount:payload.amount,currency:'INR'};return Response.json(providerOrder)}if(String(url).includes('/payments/'))return Response.json({id:providerPayment,order_id:providerOrder.id,amount:providerOrder.amount,currency:'INR',status:providerStatus});throw Error('Unexpected provider request')};const real=await call('checkout',{...input,items:[{variantId:'rose-50',quantity:1}],key:crypto.randomUUID()});providerPayment='pay_fixture';const verify={id:real.order.id,razorpay_order_id:providerOrder.id,razorpay_payment_id:providerPayment,razorpay_signature:'invalid'};await call('verify',verify,{status:400});verify.razorpay_signature=createHmac('sha256','fixture-secret').update(providerOrder.id+'|'+providerPayment).digest('hex');await call('verify',verify,{status:409});assert.equal(sqlite.prepare('SELECT payment_status FROM orders WHERE id=?').get(real.order.id).payment_status,'unpaid');providerStatus='captured';assert.equal((await call('verify',verify)).order.payment_status,'paid');await call('verify',verify);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM order_events WHERE id=?').get('paid-'+real.order.id).n,1);const raw=JSON.stringify({event:'payment.captured',payload:{payment:{entity:{id:providerPayment,order_id:providerOrder.id,amount:providerOrder.amount,currency:'INR',status:'captured'}}}});const hook=await handleCommerce(new Request('https://store.test/api/commerce/webhook',{method:'POST',body:raw,headers:{'x-razorpay-signature':createHmac('sha256','fixture-webhook').update(raw).digest('hex')}}));assert.equal(hook.status,200);const badHook=await handleCommerce(new Request('https://store.test/api/commerce/webhook',{method:'POST',body:raw,headers:{'x-razorpay-signature':'fake'}}));assert.equal(badHook.status,401);console.log('PASS: Razorpay adapter tests — forged signatures rejected, authorized-only payment held, captured payment verified, repeat verification idempotent, webhook HMAC checked. No external payment was made.');
