export class CommerceError extends Error {status:number;constructor(message:string,status=400){super(message);this.status=status}}
export function assert(condition:unknown,message:string,status=400):asserts condition{if(!condition)throw new CommerceError(message,status)}
export const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n/100);
export function cleanItems(items:unknown):{variantId:string;quantity:number}[]{assert(Array.isArray(items)&&items.length<=20,'Your bag can contain up to 20 different sizes.');const result=new Map<string,number>();for(const row of items){assert(row&&typeof row.variantId==='string'&&/^[a-z0-9-]{1,60}$/.test(row.variantId),'Invalid product selection.');assert(Number.isInteger(row.quantity)&&row.quantity>=1&&row.quantity<=10,'Choose a quantity between 1 and 10.');result.set(row.variantId,(result.get(row.variantId)||0)+row.quantity)}for(const n of result.values())assert(n<=10,'Maximum 10 of each size.');return [...result].map(([variantId,quantity])=>({variantId,quantity}))}
export function calculateTotals(lines:{price:number;quantity:number}[],promotion:any){const subtotal=lines.reduce((a,l)=>a+l.price*l.quantity,0);const discount=promotion?Math.min(Math.round(subtotal*promotion.percent/100),promotion.maximum):0;const shipping=subtotal===0||subtotal-discount>=300000?0:9900;return{subtotal,discount,shipping,total:subtotal-discount+shipping}}
export function address(input:any){assert(input&&typeof input==='object','Enter your delivery details.');const fields=['name','email','phone','line1','line2','city','state','postal'];const result:any={};for(const key of fields){assert(input[key]===undefined||typeof input[key]==='string','Invalid delivery details.');result[key]=(input[key]||'').trim();assert(result[key].length<=200,'Address fields must be under 200 characters.')}assert(result.name.length>=2,'Enter your full name.');assert(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result.email),'Enter a valid email.');assert(/^[6-9][0-9]{9}$/.test(result.phone),'Enter a 10-digit Indian mobile number.');assert(result.line1.length>=5&&result.city.length>=2&&result.state.length>=2,'Complete your delivery address.');assert(/^[1-9][0-9]{5}$/.test(result.postal),'Enter a six-digit PIN code.');return {...result,country:'India'}}
export async function hmac(secret:string,message:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return [...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(message)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function digest(value:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
export function safeEqual(a:string,b:string){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let result=0;for(let i=0;i<a.length;i++)result|=a.charCodeAt(i)^b.charCodeAt(i);return result===0}
export function transition(from:string,to:string){return ({paid:['processing'],processing:['shipped'],shipped:['delivered']} as Record<string,string[]>)[from]?.includes(to)||false}
export function escapeHtml(s:unknown){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
