import { env } from 'cloudflare:workers';
import { seedProducts } from './catalog';
import { initialContent,validateContent } from './site-content';
import { assert,CommerceError,cleanItems,calculateTotals,address,hmac,digest,safeEqual,transition,escapeHtml,money } from './commerce-core';
const E=()=>env as any,DB=()=>{assert(E().DB,'Database unavailable.',503);return E().DB as D1Database};
const now=()=>new Date().toISOString(),uid=()=>crypto.randomUUID();
const statement=(sql:string,...args:any[])=>DB().prepare(sql).bind(...args);
const one=async(sql:string,...args:any[])=>statement(sql,...args).first<any>();
const all=async(sql:string,...args:any[])=>((await statement(sql,...args).all<any>()).results||[]);
const run=async(sql:string,...args:any[])=>statement(sql,...args).run();
const json=(data:any,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
function identity(req:Request){const id=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');return id&&email?{id,email}:null}
function isAdmin(req:Request){const user=identity(req);return !!user&&((E().ADMIN_USER_IDS||'').split(',').includes(user.id)||(E().ADMIN_EMAILS||'').toLowerCase().split(',').map((x:string)=>x.trim()).filter(Boolean).includes(user.email.toLowerCase()))}
function admin(req:Request){assert(isAdmin(req),'Administrator access required.',403)}
function session(req:Request){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)shrinika_guest=([a-f0-9-]{36})/)?.[1];return token||uid()}
async function owner(req:Request,guest:string){return identity(req)?'user:'+identity(req)!.id:'guest:'+await digest(guest)}
async function readBody(req:Request){assert(Number(req.headers.get('content-length')||0)<65536,'Request too large.',413);const text=await req.text();assert(text.length<65536,'Request too large.',413);try{return JSON.parse(text)}catch{throw new CommerceError('Invalid request data.')}}
async function rate(req:Request,scope:string,limit=40){const bucket=Math.floor(Date.now()/60000);const ip=req.headers.get('cf-connecting-ip')||'unknown';const key=scope+':'+bucket+':'+await digest(ip);const r=await one('INSERT INTO rate_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count',key,bucket+2);assert(r.count<=limit,'Too many requests. Please wait a minute.',429);await run('DELETE FROM rate_limits WHERE expires < ?',bucket)}
let seeded=false;
async function seed(){if(seeded)return;const stmts:D1PreparedStatement[]=[];for(const p of seedProducts){stmts.push(statement('INSERT OR IGNORE INTO products (id,slug,name,family,description,notes,color,image,active,concept) VALUES (?,?,?,?,?,?,?,?,1,1)',p.id,p.slug,p.name,p.family,p.description,JSON.stringify(p.notes),p.color,''));[50,100].forEach((size,i)=>stmts.push(statement('INSERT OR IGNORE INTO variants(id,product_id,size,price,stock) VALUES (?,?,?,?,?)',p.id+'-'+size,p.id,size,p.prices[i],25)))}stmts.push(statement('INSERT OR IGNORE INTO promotions(code,percent,minimum,maximum,active) VALUES (?,?,?,?,1)','WELCOME10',10,150000,50000));stmts.push(statement('INSERT OR IGNORE INTO content(id,draft,published,updated_at) VALUES (?,?,?,?)','site',JSON.stringify(initialContent),JSON.stringify(initialContent),now()));await DB().batch(stmts);seeded=true}
async function settings(draft=false){const row=await one('SELECT * FROM content WHERE id=?','site');return{...initialContent,...JSON.parse(row[draft?'draft':'published'])}}
function mode(){return E().COMMERCE_MODE==='live'?'live':E().RAZORPAY_KEY_ID&&E().RAZORPAY_KEY_SECRET?'test':'demo'}
async function catalogue(includeHidden=false){const ps=await all('SELECT * FROM products '+(includeHidden?'':'WHERE active=1'));const vs=await all('SELECT * FROM variants');return ps.map(p=>({...p,notes:JSON.parse(p.notes),variants:vs.filter(v=>v.product_id===p.id)}))}
async function quote(input:any){const items=cleanItems(input.items);const lines=[];for(const item of items){const row=await one('SELECT v.*,p.name,p.slug,p.color,p.image,p.concept FROM variants v JOIN products p ON p.id=v.product_id WHERE v.id=? AND p.active=1',item.variantId);assert(row,'A product is no longer available.');assert(row.stock>=item.quantity,`${row.name}, ${row.size} ml: only ${row.stock} available.`,409);lines.push({...row,quantity:item.quantity,variantId:item.variantId})}const coupon=String(input.coupon||'').trim().toUpperCase();let promotion=null;if(coupon){promotion=await one('SELECT * FROM promotions WHERE code=? AND active=1',coupon);assert(promotion&&(!promotion.expires_at||promotion.expires_at>now()),'This promotion is unavailable or expired.');assert(lines.reduce((n,l)=>n+l.price*l.quantity,0)>=promotion.minimum,`This promotion requires a bag of ${money(promotion.minimum)}.`)}const totals=calculateTotals(lines,promotion);const site=await settings();totals.shipping=totals.subtotal===0||totals.subtotal-totals.discount>=site.freeShippingAt?0:site.shippingFee;totals.total=totals.subtotal-totals.discount+totals.shipping;return{items:lines,coupon,...totals}}
async function audit(req:Request,action:string,target:string){await run('INSERT INTO audits(id,actor,action,target,created_at) VALUES (?,?,?,?,?)',uid(),identity(req)!.id,action,target,now())}
async function accessOrder(req:Request,id:string,guest:string,token?:string){const row=await one('SELECT * FROM orders WHERE id=? OR number=?',id,id);assert(row,'Order not found.',404);const who=await owner(req,guest);const authorized=row.owner===who||(row.user_id&&row.user_id===identity(req)?.id)||isAdmin(req)||(token&&safeEqual(row.guest_hash,await digest(token)));assert(authorized,'Order not found or access code is incorrect.',404);return row}
async function orderView(row:any){const result={...row,customer:JSON.parse(row.customer),items:JSON.parse(row.items),seller:JSON.parse(row.seller),events:await all('SELECT status,message,created_at FROM order_events WHERE order_id=? ORDER BY created_at',row.id)};delete result.guest_hash;delete result.idempotency_key;delete result.owner;return result}
async function razor(path:string,body?:any){assert(E().RAZORPAY_KEY_ID&&E().RAZORPAY_KEY_SECRET,'Razorpay is not configured.',503);const r=await fetch('https://api.razorpay.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Basic '+btoa(E().RAZORPAY_KEY_ID+':'+E().RAZORPAY_KEY_SECRET),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data:any=await r.json();assert(r.ok,'The payment provider could not complete the request. Try again or contact support.',502);return data}
async function capture(row:any,payment:any,eventId:string){assert(payment.order_id===row.razorpay_order&&payment.currency==='INR'&&payment.amount===row.total,'Payment details do not match the order.',400);assert(payment.status==='captured','Payment is not captured yet. Check your order again shortly.',409);if(row.payment_status==='paid')return;const at=now();await DB().batch([statement('INSERT OR IGNORE INTO payment_events(id,order_id,kind,created_at) VALUES (?,?,?,?)',eventId,row.id,'captured',at),statement("UPDATE orders SET payment_status='paid',status=CASE WHEN status='expired' THEN 'payment_review' ELSE 'paid' END,payment_id=?,invoice_number=COALESCE(invoice_number,?),updated_at=? WHERE id=? AND payment_status<>'paid'",payment.id,'INV-'+row.number,at,row.id),statement('INSERT OR IGNORE INTO order_events(id,order_id,status,message,created_at) VALUES (?,?,?,?,?)','paid-'+row.id,row.id,'paid','Payment verified by Razorpay. Your order is confirmed.',at)])}
function invoice(row:any){const e=escapeHtml,c=JSON.parse(row.customer),seller=JSON.parse(row.seller),items=JSON.parse(row.items);return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${e(row.invoice_number||row.number)}</title><style>body{font:14px Arial;color:#292e28;max-width:850px;margin:50px auto;padding:25px}h1{letter-spacing:5px}table{width:100%;border-collapse:collapse;margin:30px 0}td,th{padding:14px 5px;text-align:left;border-bottom:1px solid #ddd}.total{text-align:right}small{color:#666}button{padding:12px;background:#293c32;color:white;border:0}@media print{button{display:none}body{margin:0}}</style></head><body><button onclick="window.print()">Print / Save PDF</button><h1>SHRINIKA</h1><h2>${row.mode==='demo'?'DEMO ORDER RECEIPT':'ORDER INVOICE'}</h2><p>${e(row.invoice_number||row.number)} · ${e(row.created_at.slice(0,10))}</p><p><b>${e(seller.sellerName)}</b><br>${e(seller.sellerAddress)}${seller.sellerGstin?'<br>GSTIN: '+e(seller.sellerGstin):''}</p><hr><h3>Bill / ship to</h3><p>${e(c.name)}<br>${e(c.line1)} ${e(c.line2)}<br>${e(c.city)}, ${e(c.state)} ${e(c.postal)}<br>${e(c.email)}</p><table><thead><tr><th>Item</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>${items.map((l:any)=>`<tr><td>${e(l.name)} · ${e(l.size)} ml</td><td>${l.quantity}</td><td>${money(l.price)}</td><td>${money(l.price*l.quantity)}</td></tr>`).join('')}</tbody></table><div class="total"><p>Subtotal ${money(row.subtotal)}</p><p>Promotion −${money(row.discount)}</p><p>Delivery ${money(row.shipping)}</p><h2>Total ${money(row.total)}</h2><p>Payment: ${e(row.payment_status)} · ${e(row.payment_id||'No payment taken')}</p></div><small>${row.mode==='demo'?'Demo only. No payment, dispatch or tax invoice.':'Commercial order receipt. Tax invoice details must be issued by the seller where applicable.'}</small></body></html>`}
export async function handleCommerce(req:Request){const path=new URL(req.url).pathname.replace('/api/commerce/','');const guest=session(req);const cookie=`shrinika_guest=${guest}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`;try{
if(path==='webhook'){assert(req.method==='POST','Method not allowed.',405);assert(E().RAZORPAY_WEBHOOK_SECRET,'Webhook is not configured.',503);const raw=await req.text();assert(raw.length<100000,'Payload too large.',413);assert(safeEqual(await hmac(E().RAZORPAY_WEBHOOK_SECRET,raw),req.headers.get('x-razorpay-signature')||''),'Invalid webhook signature.',401);const event=JSON.parse(raw),payment=event.payload?.payment?.entity;if(['payment.captured','order.paid'].includes(event.event)&&payment){const row=await one('SELECT * FROM orders WHERE razorpay_order=?',payment.order_id);assert(row,'Order not yet registered. Retry notification.',503);await capture(row,payment,req.headers.get('x-razorpay-event-id')||await digest(raw))}return json({received:true})}
if(!['GET','HEAD'].includes(req.method)){assert(req.headers.get('origin')===new URL(req.url).origin,'Cross-site request rejected.',403);await rate(req,path.startsWith('admin')?'admin':path,80)}
await seed();const who=await owner(req,guest);const respond=(data:any,status=200)=>json(data,status,{'Set-Cookie':cookie});
if(path==='bootstrap'){const user=identity(req);return respond({products:await catalogue(),content:await settings(),user:user?{...user,profile:await one('SELECT * FROM customers WHERE id=?',user.id)}:null,admin:isAdmin(req),mode:mode()})}
if(path==='cart'){if(req.method==='PUT'){const data=await readBody(req),items=cleanItems(data.items);await run('INSERT INTO carts(id,owner,items,coupon,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET items=excluded.items,coupon=excluded.coupon,updated_at=excluded.updated_at',who,who,JSON.stringify(items),String(data.coupon||'').trim().toUpperCase().slice(0,30),now())}const cart=await one('SELECT * FROM carts WHERE id=?',who);return respond(cart?{items:JSON.parse(cart.items),coupon:cart.coupon}:{items:[],coupon:''})}
if(path==='quote'&&req.method==='POST')return respond(await quote(await readBody(req)));
if(path==='profile'&&req.method==='POST'){const user=identity(req);assert(user,'Sign in to create your account.',401);const b=await readBody(req);assert(typeof b.name==='string'&&b.name.trim().length>=2&&b.name.length<=120,'Enter your name.');assert(!b.phone||/^[6-9][0-9]{9}$/.test(b.phone),'Enter a 10-digit mobile number.');await run('INSERT INTO customers(id,email,name,phone,created_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,phone=excluded.phone',user.id,user.email,b.name.trim(),b.phone||'',now());return respond({saved:true})}
if(path==='orders'&&req.method==='GET'){const user=identity(req);const rows=user?await all('SELECT * FROM orders WHERE user_id=? OR owner=? ORDER BY created_at DESC LIMIT 100',user.id,who):await all('SELECT * FROM orders WHERE owner=? ORDER BY created_at DESC LIMIT 50',who);return respond({orders:await Promise.all(rows.map(orderView))})}
if(path==='checkout'&&req.method==='POST'){const b=await readBody(req);assert(typeof b.key==='string'&&/^[a-f0-9-]{36}$/.test(b.key),'Invalid checkout reference.');const key=who+':'+b.key;let row=await one('SELECT * FROM orders WHERE idempotency_key=?',key);if(row)return respond({order:await orderView(row),keyId:mode()==='demo'?null:E().RAZORPAY_KEY_ID});const q=await quote(b);assert(q.items.length,'Your bag is empty.');const customer=address(b.customer);const site=await settings();const currentMode=mode();if(currentMode==='live'){assert(E().RAZORPAY_KEY_ID?.startsWith('rzp_live_')&&E().RAZORPAY_KEY_SECRET&&E().RAZORPAY_WEBHOOK_SECRET,'Live payment configuration is incomplete.',503);assert(site.catalogApproved&&q.items.every(i=>!i.concept)&&site.sellerAddress&&site.supportEmail,'Store catalogue and seller details must be approved before live checkout.',503)}else if(currentMode==='test')assert(E().RAZORPAY_KEY_ID.startsWith('rzp_test_'),'Use test keys in test mode.',503);
const id=uid(),number='SHR-'+Date.now().toString(36).toUpperCase()+'-'+id.slice(0,4).toUpperCase(),access=uid()+uid(),at=now();const user=identity(req);const statements=[statement('INSERT INTO orders(id,number,owner,user_id,guest_hash,idempotency_key,customer,items,subtotal,discount,shipping,total,coupon,mode,status,payment_status,seller,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,number,who,b.guest?null:user?.id||null,await digest(access),key,JSON.stringify(customer),JSON.stringify(q.items),q.subtotal,q.discount,q.shipping,q.total,q.coupon,currentMode,'payment_pending','unpaid',JSON.stringify(site),at,at),...q.items.map(i=>statement('UPDATE variants SET stock=stock-? WHERE id=?',i.quantity,i.variantId)),statement('INSERT INTO order_events(id,order_id,status,message,created_at) VALUES (?,?,?,?,?)',uid(),id,'payment_pending','Order created. Awaiting payment confirmation.',at)];try{await DB().batch(statements)}catch(error){row=await one('SELECT * FROM orders WHERE idempotency_key=?',key);if(row)return respond({order:await orderView(row),keyId:currentMode==='demo'?null:E().RAZORPAY_KEY_ID});throw new CommerceError('Stock changed while checking out. Refresh your bag and try again.',409)}
if(currentMode!=='demo'){try{const rp=await razor('orders',{amount:q.total,currency:'INR',receipt:number,notes:{shrinika_order_id:id}});await run('UPDATE orders SET razorpay_order=?,updated_at=? WHERE id=?',rp.id,now(),id)}catch(error){await run("UPDATE orders SET payment_status='provider_review' WHERE id=?",id);throw error}}
row=await one('SELECT * FROM orders WHERE id=?',id);return respond({order:await orderView(row),accessCode:access,keyId:currentMode==='demo'?null:E().RAZORPAY_KEY_ID},201)}
if(path==='demo-payment'&&req.method==='POST'){assert(mode()==='demo','Demo payment disabled.',403);const b=await readBody(req),row=await accessOrder(req,b.id,guest);assert(row.mode==='demo','Not a demo order.',403);await DB().batch([statement("UPDATE orders SET status='paid',payment_status='demo',invoice_number=?,updated_at=? WHERE id=? AND status='payment_pending'",'DEMO-'+row.number,now(),row.id),statement('INSERT OR IGNORE INTO order_events(id,order_id,status,message,created_at) VALUES (?,?,?,?,?)','demo-'+row.id,row.id,'paid','Demo order confirmed. No money was charged; nothing will be shipped.',now())]);await run('DELETE FROM carts WHERE id=?',who);return respond({order:await orderView(await one('SELECT * FROM orders WHERE id=?',row.id))})}
if(path==='verify'&&req.method==='POST'){const b=await readBody(req),row=await accessOrder(req,b.id,guest);assert(row.razorpay_order===b.razorpay_order_id,'Payment order mismatch.');assert(safeEqual(await hmac(E().RAZORPAY_KEY_SECRET,row.razorpay_order+'|'+b.razorpay_payment_id),b.razorpay_signature),'Payment verification failed.',400);const payment=await razor('payments/'+encodeURIComponent(b.razorpay_payment_id));await capture(row,payment,'verify-'+payment.id);await run('DELETE FROM carts WHERE id=?',who);return respond({order:await orderView(await one('SELECT * FROM orders WHERE id=?',row.id))})}
if(path==='track'&&req.method==='POST'){await rate(req,'tracking',10);const b=await readBody(req);assert(typeof b.number==='string'&&typeof b.accessCode==='string','Enter your order number and access code.');return respond({order:await orderView(await accessOrder(req,b.number,guest,b.accessCode))})}
if(path.startsWith('orders/')){const parts=path.split('/'),row=await accessOrder(req,parts[1],guest,new URL(req.url).searchParams.get('access')||undefined);if(parts[2]==='invoice'){assert(['paid','demo'].includes(row.payment_status),'Invoice available after payment confirmation.',409);return new Response(invoice(row),{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'"}})}return respond({order:await orderView(row)})}
if(path.startsWith('admin/')){admin(req);const action=path.slice(6);
if(action==='dashboard')return respond({products:await catalogue(true),promotions:await all('SELECT * FROM promotions ORDER BY code'),orders:await Promise.all((await all('SELECT * FROM orders ORDER BY created_at DESC LIMIT 200')).map(orderView)),content:await settings(true),published:await settings(),audit:await all('SELECT action,target,created_at FROM audits ORDER BY created_at DESC LIMIT 30'),configuration:{mode:mode(),razorpay:!!E().RAZORPAY_KEY_ID,webhook:!!E().RAZORPAY_WEBHOOK_SECRET}});
if(action==='content'&&req.method==='POST'){const b=await readBody(req),value=validateContent(b.content);await run(b.publish?'UPDATE content SET draft=?,published=?,updated_at=? WHERE id=?':'UPDATE content SET draft=?,updated_at=? WHERE id=?',...b.publish?[JSON.stringify(value),JSON.stringify(value),now(),'site']:[JSON.stringify(value),now(),'site']);await audit(req,b.publish?'Published page content':'Saved content draft','site');return respond({saved:true})}
if(action==='product'&&req.method==='POST'){const b=await readBody(req);for(const field of ['id','slug'])assert(typeof b[field]==='string'&&/^[a-z0-9-]{1,60}$/.test(b[field]),'Use lowercase letters, numbers and hyphens for product IDs and slugs.');for(const field of ['name','family','description','color'])assert(typeof b[field]==='string'&&b[field].length>0&&b[field].length<4000,'Complete all product fields.');assert(b.notes&&['top','heart','base'].every(k=>typeof b.notes[k]==='string'&&b.notes[k].length<=500),'Complete the fragrance notes.');assert(!b.image||/^https:\/\//.test(b.image)||/^\/media\/[a-zA-Z0-9.-]+$/.test(b.image),'Use a secure image URL or upload.');assert(Array.isArray(b.variants)&&b.variants.length>=1&&b.variants.length<=6,'Add 1–6 sizes.');const stmts=[statement('INSERT INTO products(id,slug,name,family,description,notes,color,image,active,concept) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,name=excluded.name,family=excluded.family,description=excluded.description,notes=excluded.notes,color=excluded.color,image=excluded.image,active=excluded.active,concept=excluded.concept',b.id,b.slug,b.name,b.family,b.description,JSON.stringify(b.notes),b.color,b.image||'',b.active?1:0,b.concept?1:0)];for(const v of b.variants){assert(Number.isInteger(v.size)&&v.size>0&&v.size<=1000&&Number.isInteger(v.price)&&v.price>0&&v.price<=100000000&&Number.isInteger(v.stock)&&v.stock>=0&&v.stock<=100000,'Check size, price and inventory.');const variantId=b.id+'-'+v.size;stmts.push(statement('INSERT INTO variants(id,product_id,size,price,stock) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET price=excluded.price,stock=excluded.stock',variantId,b.id,v.size,v.price,v.stock))}await DB().batch(stmts);await audit(req,'Updated product and inventory',b.id);return respond({saved:true})}
if(action==='promotion'&&req.method==='POST'){const b=await readBody(req);assert(/^[A-Z0-9]{3,24}$/.test(b.code),'Use 3–24 uppercase letters or numbers.');assert(Number.isInteger(b.percent)&&b.percent>0&&b.percent<=80,'Discount must be 1–80%.');assert(Number.isInteger(b.minimum)&&b.minimum>=0&&Number.isInteger(b.maximum)&&b.maximum>0,'Check promotion limits.');assert(!b.expires_at||Number.isFinite(Date.parse(b.expires_at)),'Invalid expiry date.');await run('INSERT INTO promotions(code,percent,minimum,maximum,active,expires_at) VALUES (?,?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET percent=excluded.percent,minimum=excluded.minimum,maximum=excluded.maximum,active=excluded.active,expires_at=excluded.expires_at',b.code,b.percent,b.minimum,b.maximum,b.active?1:0,b.expires_at||null);await audit(req,'Updated promotion',b.code);return respond({saved:true})}
if(action==='order'&&req.method==='POST'){const b=await readBody(req),row=await one('SELECT * FROM orders WHERE id=?',b.id);assert(row,'Order not found.',404);assert(['paid','demo'].includes(row.payment_status),'Only confirmed orders can be fulfilled.');assert(transition(row.status,b.status),'Invalid order status transition.');if(b.status==='shipped'){assert(typeof b.carrier==='string'&&b.carrier.length>0&&b.carrier.length<100&&typeof b.trackingNumber==='string'&&b.trackingNumber.length>0&&b.trackingNumber.length<100,'Enter carrier and tracking number.');assert(!b.trackingUrl||/^https:\/\//.test(b.trackingUrl),'Tracking URL must start with HTTPS.')}await DB().batch([statement('UPDATE orders SET status=?,carrier=COALESCE(?,carrier),tracking_number=COALESCE(?,tracking_number),tracking_url=COALESCE(?,tracking_url),updated_at=? WHERE id=? AND status=?',b.status,b.carrier||null,b.trackingNumber||null,b.trackingUrl||null,now(),b.id,row.status),statement('INSERT INTO order_events(id,order_id,status,message,created_at) VALUES (?,?,?,?,?)',uid(),b.id,b.status,({processing:'Your order is being prepared.',shipped:'Your parcel has been handed to the carrier.',delivered:'Delivery marked complete by the store.'} as any)[b.status],now())]);await audit(req,'Order '+b.status,b.id);return respond({saved:true})}
if(action==='reconcile'&&req.method==='POST'){const b=await readBody(req),row=await one('SELECT * FROM orders WHERE id=?',b.id);assert(row?.razorpay_order,'No provider order to reconcile.');const payments=await razor('orders/'+row.razorpay_order+'/payments');const payment=payments.items?.find((p:any)=>p.status==='captured');assert(payment,'No captured payment found.',409);await capture(row,payment,'reconcile-'+payment.id);await audit(req,'Reconciled payment',row.id);return respond({saved:true})}
if(action==='upload'&&req.method==='POST'){assert(E().BUCKET,'Media storage is not available.',503);const data=await req.arrayBuffer();assert(data.byteLength>12&&data.byteLength<=8000000,'Choose an image smaller than 8 MB.');const bytes=new Uint8Array(data);let ext='',type='';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255){ext='jpg';type='image/jpeg'}else if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71){ext='png';type='image/png'}else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP'){ext='webp';type='image/webp'}assert(ext,'Upload a JPG, PNG or WebP image.');const key=uid()+'.'+ext;await E().BUCKET.put(key,data,{httpMetadata:{contentType:type}});await audit(req,'Uploaded image',key);return respond({url:'/media/'+key})}
throw new CommerceError('Admin action not found.',404)}
throw new CommerceError('Not found.',404)
}catch(error:any){const status=error instanceof CommerceError?error.status:500;if(status===500)console.error('Commerce request failed',path,error?.message);return json({error:status===500?'We could not complete that request. Please try again.':error.message},status,{'Set-Cookie':cookie})}}
